---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r load packages, message = FALSE}
library(data.table)

library(sandwich)
library(lmtest)

library(AER) 
library(dplyr)


library(ggplot2) 
library(patchwork)

library(MatchIt)
library(optmatch)
```

```{r load draft data}
#Read in the data
d <- fread('../Data/joined_results_2nd_run.tsv')


head(d)
names(d)
```



```{r}
#Filter to where user input property == potential response Property
d_filtered = d
d_filtered
```



```{r}
#For every row, create a column that is the value difference of white to non white
#i.e. If race==white of response, abs_value_diff, else use -abs_value_diff

#Using data.table fifelse
d_filtered[abs_value_diff==0,abs_value_diff := 0.5]
d_filtered[ , white_value_diff := fifelse(nb_race=="white", abs_value_diff, -abs_value_diff)]

d_filtered[ ,log_abs_diff := log(abs_value_diff)]
d_filtered[, log_white_diff := fifelse(nb_race=="white", log_abs_diff, -log_abs_diff)]


#Create a column with 0/1 if neighborhood is white
d_filtered[ , nb_is_white := fifelse(nb_race=="white", 1, 0)]

```

```{r}
d_filtered
```

```{r}
#Create a variable for whether street view contained a person

d_filtered[ , street_view_person := rep(0, .N)]

#Change Property 1 & 3s to 1
d_filtered[ (property_chosen == "Property 1") & (question == "3s") , street_view_person := 1] 

#Change both Properties of 10s to 1
d_filtered[  (question == "10s") , street_view_person := 1] 

#Change property 2 of 11s to 1
d_filtered[  (property_chosen == "Property 2") &(question == "11s") , street_view_person := 1] 

#Change property 1 of 13s to 1
d_filtered[  (property_chosen == "Property 1") &(question == "13s") , street_view_person := 1] 

#Change property 2 of 14s to 1
d_filtered[  (property_chosen == "Property 2") &(question == "14s") , street_view_person := 1] 

#Change property 1&2 of 18s to 1
d_filtered[  (question == "18s") , street_view_person := 1] 

#Change property 1 of 20s to 1
d_filtered[  (property_chosen == "Property 1") &(question == "20s") , street_view_person := 1] 

#Change property 1 of 25s to 1
d_filtered[  (property_chosen == "Property 1") &(question == "25s") , street_view_person := 1] 


d_filtered
```


```{r}
ggplot(data =d_filtered[ treatment==0, ], aes(d_filtered[ treatment==0, white_value_diff])) + geom_histogram()
```



```{r}
ggplot(data =d_filtered[ treatment==1, ], aes(d_filtered[ treatment==1, white_value_diff])) + geom_histogram()
```

```{r}
fwrite(d_filtered, "../Data/filtered_data_2.csv")
```

```{r}
df = data.table::fread("../Data/filtered_data_2.csv")
df
names(df)
```

``` {r}
by_person = df[!duplicated(df$id), ] 
by_person
```

``` {r}
m.out <- matchit(treatment ~ sexual_orientation + age + marital_status + demographic_race
                  + gender + ethnicity, data = by_person,
                 method = "full")
m.out
```

```{r}
plot(m.out, type = "qq", which.xs = c("age", "education", "sexual_orientation"))
```

``` {r}
summary(m.out, pair.dist = FALSE)
```

```{r}
typeof(df)
#Some attempts at writing a model


#For each question, we want the difference in counts of properties selected by is_white
new_df = df[ , .(count=.N), keyby=.(question, nb_is_white, treatment) ]
new_df


#We want to predict the difference of the counts of the is_white or not properties for each question
new_df[ , is_white_count:= diff(count, lag=1), keyby = .(question, treatment)]
new_df

model = new_df[ , lm(is_white_count ~ treatment)]

coeftest(model,  vcov = vcovCL(model, cluster = new_df[ , question]))
```

## Proportion Models

```{r}
prop_white_model = df[, lm(nb_is_white ~ treatment + as.factor(id))]
coeftest(prop_white_model,  vcov = vcovCL(prop_white_model, cluster = df[ , as.factor(id)]))
stargazer::stargazer(prop_white_model, header = T, type='html', se = list(NULL,sqrt(diag(vcovCL(prop_white_model, cluster = df[ , as.factor(id)])))),out='prop_white_model_table.html')
```

```{r}
prop_white_model_no_id = df[, lm(nb_is_white ~ treatment)]
coeftest(prop_white_model_no_id)
stargazer::stargazer(prop_white_model_no_id, header = T, type='html',out='prop_white_model_no_id_table.html')
```

```{r}
prop_white_model_cluster_no_id = df[, lm(nb_is_white ~ treatment)]
coeftest(prop_white_model_cluster_no_id,  vcov = vcovCL(prop_white_model_cluster_no_id))
stargazer::stargazer(prop_white_model_cluster_no_id, header = T, type='html', se = list(NULL,sqrt(diag(vcovCL(prop_white_model_cluster_no_id, cluster = df[ , as.factor(id)])))),out='prop_white_model_cluster_no_id_table.html')
```

```{r}
prop_white_model = df[, lm(nb_is_white ~ treatment + as.factor(id))]
coeftest(prop_white_model)
stargazer::stargazer(prop_white_model, header = T, type='html',out='prop_white_model_table.html')
plot(prop_white_model)
```

```{r}
prop_white_model_demo = df[, lm(nb_is_white ~ treatment + as.factor(demographic_race) + as.factor(ethnicity) + as.factor(gender) + age  + as.factor(education) + as.factor(residency_type) + as.factor(ownership) + as.factor(RE_job) + as.factor(id))]
coeftest(prop_white_model_demo)
stargazer::stargazer(prop_white_model_demo, header = T, type='html',out='prop_white_model_demo_table.html')

coeftest(prop_white_model_demo,  vcov = vcovCL(prop_white_model_demo))
```

```{r}
prop_white_model_demo_no_id = df[, lm(nb_is_white ~ treatment + as.factor(demographic_race) + as.factor(ethnicity) + as.factor(gender) + age  + as.factor(education) + as.factor(residency_type) + as.factor(ownership) + as.factor(RE_job))]
coeftest(prop_white_model_demo_no_id)
stargazer::stargazer(prop_white_model_demo_no_id, header = T, type='html',out='prop_white_model_demo_no_id_table.html')
```

```{r}
stargazer::stargazer(prop_white_model_no_id, prop_white_model_demo_no_id, prop_white_model, prop_white_model_demo, header = T, type='html',out='prop_combined_table.html')
```

```{r}
df[,.N, by=nb_race]
```

## Value Difference models

```{r}
value_model = df[, lm(white_value_diff ~ treatment + as.factor(id))]
coeftest(value_model,  vcov = vcovCL(value_model, cluster = df[ , as.factor(id)]))
stargazer::stargazer(value_model, header = T, type='html', se = list(NULL,sqrt(diag(vcovCL(value_model, cluster = df[ , as.factor(id)])))),out='value_model_table.html')
```

```{r}
value_model_log = df[, lm(log(white_value_diff) ~ treatment + as.factor(id))]

coeftest(value_model_log,  vcov = vcovCL(value_model_log, cluster = df[ , as.factor(id)]))
coeftest(value_model_log, se = sqrt(diag(vcovCL(value_model_log, cluster = df[ , as.factor(id)]))))

stargazer::stargazer(value_model_log, header = T, type='html', se = list(NULL,sqrt(diag(vcovCL(value_model_log, cluster = df[ , as.factor(id)])))),out='value_model_log_table.html')

```

```{r}
value_model_no_cluster = df[, lm(log(white_value_diff) ~ treatment + as.factor(id))]

coeftest(value_model_no_cluster)
summary(value_model_no_cluster)
stargazer::stargazer(value_model_no_cluster, header = T, type='html',out='value_model_no_cluster_table.html')

plot(value_model_no_cluster)

```

```{r}
value_model_no_id = df[, lm(log(white_value_diff) ~ treatment)]

coeftest(value_model_no_id)

stargazer::stargazer(value_model_no_id, header = T, type='html',out='value_model_no_id_table.html')
```

```{r}
value_model_cluster_no_id = df[, lm(log(white_value_diff) ~ treatment)]

coeftest(value_model_cluster_no_id, se = sqrt(diag(vcovCL(value_model_log, cluster = df[ , as.factor(id)]))))

stargazer::stargazer(value_model_cluster_no_id, header = T, type='html', se = list(NULL,sqrt(diag(vcovCL(value_model_log, cluster = df[ , as.factor(id)])))),out='value_model_cluster_no_id_table.html')
```

```{r}
value_model_demo = df[, lm(log(white_value_diff) ~ treatment + as.factor(demographic_race) + as.factor(ethnicity) + as.factor(gender) + age  + as.factor(education) + as.factor(residency_type) + as.factor(ownership) + as.factor(RE_job) + as.factor(id))]

coeftest(value_model_demo)
stargazer::stargazer(value_model_demo, header = T, type='html',out='value_model_demo_table.html')

```

```{r}
value_model_demo_no_id = df[, lm(log(white_value_diff) ~ treatment + as.factor(demographic_race) + as.factor(ethnicity) + as.factor(gender) + age  + as.factor(education) + as.factor(residency_type) + as.factor(ownership) + as.factor(RE_job))]

coeftest(value_model_demo_no_id)
stargazer::stargazer(value_model_demo_no_id, header = T, type='html',out='value_model_demo_no_id_table.html')
```


```{r}
stargazer::stargazer(value_model_no_id, value_model_demo_no_id, value_model_log, value_model_demo, header = T, type='html',out='value_combined_table.html')
```

```{r}
df
df[order(Pair_ID),mean(nb_is_white), by=.(Pair_ID,treatment)][,mean(V1), by=treatment]
```













