---
title: "R Notebook"
output: html_notebook
---

```{r load packages, message = FALSE}
library(data.table)

library(sandwich)
library(lmtest)
library(AER) 
library(dplyr)


library(ggplot2) 

library(patchwork)

library("MatchIt")
```

```{r load draft data}
#Read in the data
#d <- fread('joined_results.tsv')

d <- fread('joined_results_2nd_run.tsv')


head(d)
names(d)
```

```{r}
#Not needed with 2nd run tsv

#Joined data contains 2 rows per response per person
#Filter out the row that does not match their response

#Convert Property (i.e. Potential Answer) to a character from an int
#d[ , Property := paste("Property", as.character(Property))]
#d
```

```{r}
#Not needed with 2nd run tsv

#Filter to where user input property == potential response Property
# d_filtered = d[ property == Property , ]
# d_filtered
```



```{r}
#For every row, create a column that is the value difference of white to non white
#i.e. If race==white of response, abs_value_diff, else use -abs_value_diff

#Using data.table fifelse
d[ , white_value_diff := fifelse(race_y=="white", abs_value_diff, -abs_value_diff)]


#Create a column with 0/1 if neighborhood is white
d[ , is_white := fifelse(race_y=="white", 1, 0)]

```

```{r}
#Create a variable for whether street view contained a person

d[ , street_view_person := rep(0, .N)]

#Change Property 1 & 3s to 1
d[ (property_chosen == "Property 1") & (question == "3s") , street_view_person := 1] 

#Change both Properties of 10s to 1
d[  (question == "10s") , street_view_person := 1] 

#Change property 2 of 11s to 1
d[  (property_chosen == "Property 2") &(question == "11s") , street_view_person := 1] 

#Change property 1 of 13s to 1
d[  (property_chosen == "Property 1") &(question == "13s") , street_view_person := 1] 

#Change property 2 of 14s to 1
d[  (property_chosen == "Property 2") &(question == "14s") , street_view_person := 1] 

#Change property 1&2 of 18s to 1
d[  (property_chosen == "18s") , street_view_person := 1] 

#Change property 1 of 20s to 1
d[  (property_chosen == "Property 1") &(question == "20s") , street_view_person := 1] 

#Change property 1 of 25s to 1
d[  (property_chosen == "Property 1") &(question == "25s") , street_view_person := 1] 


d
```


```{r}
ggplot(data =d_filtered[ treatment==0, ], aes(d_filtered[ treatment==0, white_value_diff])) +
  geom_histogram()
```



```{r}
ggplot(data =d_filtered[ treatment==1, ], aes(d_filtered[ treatment==1, white_value_diff])) +
  geom_histogram()
```

```{r}
fwrite(d_filtered, "filtered_data.csv")
```

```{r}
df = data.table::fread("filtered_data.csv")
df
names(df)
```

```{r}
df = d

typeof(df)
#Some attempts at writing a model


#For each question, we want the difference in counts of properties selected by is_white
new_df = df[ , .(count=.N), keyby=.(question, is_white, treatment) ]
new_df


#We want to predict the difference of the counts of the is_white or not properties for each question
new_df[ , is_white_count:= diff(count, lag=1), keyby = .(question, treatment)]
new_df

model = new_df[ , lm(is_white_count ~ treatment)]

coeftest(model,  vcov = vcovCL(model, cluster = new_df[ , question]))
```

```{r}
is_white_model = df[, lm(is_white ~ treatment + as.factor(id))]
coeftest(is_white_model,  vcov = vcovCL(is_white_model, cluster = df[ , as.factor(id)]))
```


```{r}
value_model = df[, lm(white_value_diff ~ treatment + as.factor(id))]
coeftest(value_model,  vcov = vcovCL(value_model, cluster = df[ , as.factor(id)]))
```

```{r}

```

```{r}
#m.out <- matchit(treatment ~ tk + tk, data = d_filtered, method = "full")
```








